---
- name: Testing VyOS
  hosts: vyos-servers
  gather_facts: true
  connection: local

  tasks:
    - name: Show the Configuration
      vyos_command:
        commands:
          - show configuration commands
