- name: Testing VyOS
  hosts: vyos-servers
  gather_facts: True
  connection: ansible.netcommon.network_cli
  
  tasks:
  - name: Show the Configuration
    vyos.vyos.vyos_command:
     commands:
       - show configuration commands
